name: Main Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.12"
      run_tests: true

  docker-latest:
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: vaishnavinalawade/github-actions-capstone
      tag: latest
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  prepare:
    needs: build-test
    runs-on: ubuntu-latest

    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}

    steps:
      - name: Generate short SHA
        id: sha
        run: |
          echo "short_sha=$(echo '${{ github.sha }}' | cut -c1-7)" >> "$GITHUB_OUTPUT"

  docker-sha:
    needs: prepare
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: vaishnavinalawade/github-actions-capstone
      tag: sha-${{ needs.prepare.outputs.short_sha }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs:
      - docker-latest
      - docker-sha

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Deploy
        run: |
          echo "Deploying image: ${{ needs.docker-latest.outputs.image_url }} to production"
